language: cpp

install: true

script:
  - mkdir build && cd build && cmake .. && make
  - ./radixSort 1000
  - ./radixSort 10000
  - ./radixSort 50000
  - ./radixSort 1000000
  - ./radixSort 10000000

notifications:
  slack: j0ny:tlJolYCjWs5eI2DmeZFry8sa
