language: cpp

install: true

script:
  - mkdir build && cd build && cmake .. && make
  - ./radixSort 100
  - ./radixSort 500
  - ./radixSort 600
  - ./radixSort 700
  - ./radixSort 800
  - ./radixSort 900
  - ./radixSort 1000
  - ./radixSort 10000

notifications:
  slack: j0ny:tlJolYCjWs5eI2DmeZFry8sa
